# Generated by Django 4.2.5 on 2023-09-20 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_complaint', models.CharField(choices=[('traffic_violation', 'Traffic Violation'), ('delayed_services', 'Delayed Services'), ('service_quality', 'Service Quality'), ('service_denial', 'Service Denial'), ('missuse_of_funds', 'Missuse of Funds'), ('road_and_transportation_issues', 'Road and Transportation Issues'), ('healthcare_services', 'Healthcare Services'), ('misconduct_allegations', 'Misconduct Allegations'), ('abuse_of_power', 'Abuse of Power'), ('other', 'Other')], max_length=100)),
                ('created_at', models.DateTimeField()),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
