# Generated by Django 4.2.5 on 2023-09-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='action_taken',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
